OPPORTUNITY_TERMS = [
    "intern",
    "internship",
    "co-op",
    "coop",
    "summer",
    "estágio",
    "estagio",
    "estagiário",
    "estagiario",
    "trainee",
    "undergraduate",
    "student",
    "programa de estágio",
    "programa de estagio",
]

EE_CORE_TERMS = [
    "electrical engineering",
    "engenharia elétrica",
    "engenharia eletrica",
    "electrical engineer",
    "engenheiro elétrico",
    "engenheiro eletrico",
    "electrical",
    "electronics",
    "eletrônica",
    "eletronica",
    "eletrotécnica",
    "eletrotecnica",
    "power electronics",
    "power systems",
    "electrical systems",
    "electric power",
]

EE_RELATED_TERMS = [
    "embedded",
    "firmware",
    "hardware",
    "pcb",
    "fpga",
    "asic",
    "rf",
    "radio frequency",
    "signal processing",
    "controls",
    "control systems",
    "automation",
    "automação",
    "automacao",
    "instrumentation",
    "instrumentação",
    "instrumentacao",
    "robotics",
    "robótica",
    "robotica",
    "mechatronics",
    "mechatronic",
    "mecatrônica",
    "mecatronica",
    "energy",
    "energia",
    "renewable",
    "solar",
    "photovoltaic",
    "fotovoltaico",
    "battery",
    "batteries",
    "electric vehicle",
    "electric vehicles",
    "ev",
    "semiconductor",
    "semiconductors",
    "avionics",
    "aviônica",
    "avionica",
    "telecommunications",
    "telecom",
    "telecomunicações",
    "telecomunicacoes",
    "microelectronics",
    "microeletrônica",
    "microeletronica",
    "circuit",
    "circuits",
    "circuit design",
    "power delivery",
    "electromagnetics",
    "plc",
    "sistemas embarcados",
    "controle e automação",
    "controle e automacao",
    "engenharia de energia",
]

NEGATIVE_TITLE_TERMS = [
    "senior",
    "sênior",
    "sr.",
    "sr ",
    "staff",
    "principal",
    "manager",
    "gerente",
    "director",
    "diretor",
    "lead ",
    "líder",
    "lider",
    "head of",
    "vice president",
    "vp ",
    "especialista",
]

NEGATIVE_REQUIREMENT_TERMS = [
    "5+ years",
    "6+ years",
    "7+ years",
    "8+ years",
    "10+ years",
    "5 anos de experiência",
    "5 anos de experiencia",
    "phd required",
    "doctorate required",
]
