"""Registry of public SAP SuccessFactors career sites.

v3.13.1 supports classic RMK tiles and the newer CSB Unified Search JSON API.
"""

SUCCESSFACTORS_PORTALS = [{'id': 'ternium',
  'name': 'Ternium',
  'enabled': True,
  'career_url': 'https://carrera.ternium.com/',
  'listing_urls': ['https://carrera.ternium.com/go/Nossas-Oportunidades/8723700/'],
  'queries': ['',
              'estágio de verão',
              'estágio de férias',
              'programa de férias',
              'summer internship',
              'estágio',
              'trainee'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'sap',
  'name': 'SAP',
  'career_url': 'https://jobs.sap.com/',
  'listing_urls': ['https://jobs.sap.com/go/Brazil/8806901/'],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'anglogold_ashanti',
  'name': 'AngloGold Ashanti',
  'career_url': 'https://careers.anglogoldashanti.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'seagate',
  'name': 'Seagate Technology',
  'career_url': 'https://seagatecareers.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'akzonobel',
  'name': 'AkzoNobel',
  'career_url': 'https://careers.akzonobel.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'epiroc',
  'name': 'Epiroc',
  'career_url': 'https://www.careerprofile.epiroc.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'metso',
  'name': 'Metso',
  'career_url': 'https://careers.metso.com/',
  'listing_urls': ['https://careers.metso.com/search/'],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'alstom',
  'name': 'Alstom',
  'career_url': 'https://jobsearch.alstom.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'skf',
  'name': 'SKF',
  'career_url': 'https://career.skf.com/',
  'listing_urls': ['https://career.skf.com/go/'],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'kerry',
  'name': 'Kerry',
  'career_url': 'https://vacancies.kerry.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'danfoss',
  'name': 'Danfoss',
  'career_url': 'https://jobs.danfoss.com/',
  'listing_urls': ['https://jobs.danfoss.com/search/',
                   'https://jobs.danfoss.com/go/Early-Talents-Internships%2C-Student-Jobs-and-Master-Thesis-Collaboration/9811257/'],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['en_GB', 'en_US', 'pt_BR']},
 {'id': 'clariant',
  'name': 'Clariant',
  'career_url': 'https://careers.clariant.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'solvay',
  'name': 'Solvay',
  'career_url': 'https://careers.solvay.com/',
  'listing_urls': ['https://careers.solvay.com/go/'],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'atlas_copco',
  'name': 'Atlas Copco',
  'career_url': 'https://www.careers.homeofindustrialideas.com/',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'voith',
  'name': 'Voith Group',
  'career_url': 'https://jobs.voith.com/',
  'listing_urls': ['https://jobs.voith.com/go/Profissionais/399482/'],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'delaval',
  'name': 'DeLaval',
  'career_url': 'https://career5.successfactors.eu/career?company=C0001122692P',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'amkor',
  'name': 'Amkor Technology',
  'career_url': 'https://career8.successfactors.com/career?company=amkor',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'basf',
  'name': 'BASF',
  'career_url': 'https://www.basf.com/global/en/careers',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16},
 {'id': 'tetra_pak',
  'name': 'Tetra Pak',
  'career_url': 'https://www.tetrapak.com/about-tetra-pak/careers',
  'listing_urls': [],
  'enabled': False,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16}]
