# Registry of public SAP SuccessFactors career sites.
# v3.15.3 repair: all known tenants enabled + EY + Volvo Group.

SUCCESSFACTORS_PORTALS = [{'id': 'ternium',
  'name': 'Ternium',
  'enabled': True,
  'career_url': 'https://carrera.ternium.com/',
  'listing_urls': ['https://carrera.ternium.com/go/Nossas-Oportunidades/8723700/'],
  'queries': ['',
              'estágio de verão',
              'estágio de férias',
              'programa de férias',
              'summer internship',
              'estágio',
              'trainee'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'sap',
  'name': 'SAP',
  'career_url': 'https://jobs.sap.com/',
  'listing_urls': ['https://jobs.sap.com/go/Brazil/8806901/'],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'anglogold_ashanti',
  'name': 'AngloGold Ashanti',
  'career_url': 'https://careers.anglogoldashanti.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'seagate',
  'name': 'Seagate Technology',
  'career_url': 'https://seagatecareers.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'akzonobel',
  'name': 'AkzoNobel',
  'career_url': 'https://careers.akzonobel.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'epiroc',
  'name': 'Epiroc',
  'career_url': 'https://www.careerprofile.epiroc.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'metso',
  'name': 'Metso',
  'career_url': 'https://careers.metso.com/',
  'listing_urls': ['https://careers.metso.com/search/'],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'alstom',
  'name': 'Alstom',
  'career_url': 'https://jobsearch.alstom.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'skf',
  'name': 'SKF',
  'career_url': 'https://career.skf.com/',
  'listing_urls': ['https://career.skf.com/go/'],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'kerry',
  'name': 'Kerry',
  'career_url': 'https://vacancies.kerry.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'danfoss',
  'name': 'Danfoss',
  'career_url': 'https://jobs.danfoss.com/',
  'listing_urls': ['https://jobs.danfoss.com/search/',
                   'https://jobs.danfoss.com/go/Early-Talents-Internships%2C-Student-Jobs-and-Master-Thesis-Collaboration/9811257/'],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['en_GB', 'en_US', 'pt_BR'],
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'clariant',
  'name': 'Clariant',
  'career_url': 'https://careers.clariant.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'solvay',
  'name': 'Solvay',
  'career_url': 'https://careers.solvay.com/',
  'listing_urls': ['https://careers.solvay.com/go/'],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'atlas_copco',
  'name': 'Atlas Copco',
  'career_url': 'https://www.careers.homeofindustrialideas.com/',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'voith',
  'name': 'Voith Group',
  'career_url': 'https://jobs.voith.com/',
  'listing_urls': ['https://jobs.voith.com/go/Profissionais/399482/'],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'delaval',
  'name': 'DeLaval',
  'career_url': 'https://career5.successfactors.eu/career?company=C0001122692P',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'amkor',
  'name': 'Amkor Technology',
  'career_url': 'https://career8.successfactors.com/career?company=amkor',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'basf',
  'name': 'BASF',
  'career_url': 'https://www.basf.com/global/en/careers',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'tetra_pak',
  'name': 'Tetra Pak',
  'career_url': 'https://www.tetrapak.com/about-tetra-pak/careers',
  'listing_urls': [],
  'enabled': True,
  'queries': ['',
              'estágio',
              'intern',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'zf',
  'name': 'ZF Group',
  'enabled': True,
  'career_url': 'https://jobs.zf.com/',
  'listing_urls': ['https://jobs.zf.com/go/Students/3636101/',
                   'https://jobs.zf.com/go/All-Jobs/3630801/'],
  'queries': ['',
              'estágio',
              'intern',
              'internship',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'schaeffler',
  'name': 'Schaeffler',
  'enabled': True,
  'career_url': 'https://jobs.schaeffler.com/',
  'listing_urls': ['https://jobs.schaeffler.com/?locale=pt_BR&currentPage=1&pageSize=30'],
  'queries': ['',
              'estágio',
              'intern',
              'internship',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['pt_BR', 'en_US', 'de_DE'],
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'scania',
  'name': 'Scania / TRATON',
  'enabled': True,
  'career_url': 'https://jobs.scania.com/',
  'listing_urls': ['https://jobs.scania.com/go/Empregos-na-Scania/9097401/',
                   'https://jobs.scania.com/go/Jobs-at-Scania_/9096801/'],
  'queries': ['',
              'estágio',
              'intern',
              'internship',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['pt_BR', 'en_US'],
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'andritz',
  'name': 'ANDRITZ',
  'enabled': True,
  'career_url': 'https://careers.andritz.com/',
  'listing_urls': ['https://careers.andritz.com/go/Professionals_br/925702/',
                   'https://careers.andritz.com/go/Professionals/924202/'],
  'queries': ['',
              'estágio',
              'intern',
              'internship',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['pt_BR', 'en_US'],
  'bootstrap_max_pages': 8,
  'bootstrap_max_listing_urls': 12,
  'bootstrap_max_details': 25},
 {'id': 'ey',
  'name': 'EY',
  'enabled': True,
  'career_url': 'https://careers.ey.com/',
  'listing_urls': ['https://careers.ey.com/viewalljobs/?locale=pt_BR',
                   'https://careers.ey.com/search/?locale=pt_BR'],
  'queries': ['',
              'estágio',
              'intern',
              'internship',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior',
              'graduate'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['pt_BR', 'en_US'],
  'bootstrap_max_pages': 5,
  'bootstrap_max_listing_urls': 8,
  'bootstrap_max_details': 20},
 {'id': 'volvo_group',
  'name': 'Volvo Group',
  'enabled': True,
  'career_url': 'https://jobs.volvogroup.com/',
  'listing_urls': ['https://jobs.volvogroup.com/search/',
                   'https://jobs.volvogroup.com/viewalljobs/'],
  'queries': ['',
              'estágio',
              'intern',
              'internship',
              'summer internship',
              'estágio de férias',
              'estágio de verão',
              'trainee',
              'aprendiz',
              'junior',
              'graduate'],
  'page_size': 25,
  'max_pages_per_query': 4,
  'max_jobs': 5000,
  'max_details': 60,
  'ats': 'successfactors',
  'universal_discovery': True,
  'try_xml_feed': True,
  'keyword_fallback': True,
  'max_listing_urls': 80,
  'max_pages_per_listing': 200,
  'show_discovery_stats': True,
  'try_tile_search': True,
  'try_csb_json': True,
  'max_tile_pages': 100,
  'max_csb_pages_per_locale': 100,
  'max_csb_locales': 16,
  'csb_locales': ['pt_BR', 'en_US'],
  'bootstrap_max_pages': 5,
  'bootstrap_max_listing_urls': 8,
  'bootstrap_max_details': 20}]

# CPFL Energia uses a public SuccessFactors/RMK career site.
SUCCESSFACTORS_PORTALS.append({
    "id": "cpfl",
    "name": "CPFL Energia",
    "enabled": True,
    "career_url": "https://vagas.cpfl.com.br/",
    "listing_urls": ["https://vagas.cpfl.com.br/viewalljobs/"],
    "queries": [
        "",
        "estágio",
        "estagiário",
        "intern",
        "trainee",
        "aprendiz",
        "junior",
        "júnior",
    ],
    "page_size": 25,
    "max_pages_per_query": 4,
    "max_jobs": 1000,
    "max_details": 40,
    "ats": "successfactors",
    "universal_discovery": True,
    "try_xml_feed": True,
    "keyword_fallback": True,
    "max_listing_urls": 12,
    "max_pages_per_listing": 40,
    "show_discovery_stats": True,
    "try_tile_search": True,
    "try_csb_json": True,
    "max_tile_pages": 40,
    "max_csb_pages_per_locale": 40,
    "max_csb_locales": 6,
    "csb_locales": ["pt_BR", "en_US"],
    "bootstrap_max_pages": 5,
    "bootstrap_max_listing_urls": 6,
    "bootstrap_max_details": 20,
})

# Regional priority. Both portals expose the existing public SAP/RMK contract.
for portal_id, name, career_url in (
    ("citrosuco", "Citrosuco", "https://carreiras.citrosuco.com.br/"),
    ("volkswagen", "Volkswagen Group", "https://jobs.volkswagen-group.com/"),
):
    SUCCESSFACTORS_PORTALS.insert(0, {
        "id": portal_id, "name": name, "career_url": career_url,
        "enabled": True, "ats": "successfactors",
        "listing_urls": [career_url + "search/", career_url + "viewalljobs/"],
        "queries": ["", "estágio", "intern", "trainee", "aprendiz", "junior"],
        "page_size": 25, "max_jobs": 1000, "max_details": 25,
        "universal_discovery": True, "try_xml_feed": True,
        # CSB JSON returned 401 on these two public portals; RMK HTML works.
        "try_tile_search": True, "try_csb_json": False, "keyword_fallback": True,
        "max_pages_per_listing": 10, "max_listing_urls": 6,
        "max_tile_pages": 10, "max_csb_pages_per_locale": 10,
        "max_csb_locales": 2, "csb_locales": ["pt_BR", "en_US"],
        "bootstrap_max_pages": 5, "bootstrap_max_details": 20,
        "bootstrap_max_listing_urls": 6,
        "show_discovery_stats": True,
    })

# CP2.8: official vacancy portals replacing corporate/legacy landing pages.
for portal in SUCCESSFACTORS_PORTALS:
    corrected = {
        "delaval": ("https://delaval-careers.jobs.hr.cloud.sap/", "en_US"),
        "basf": ("https://basf.jobs/", "en_US"),
        "tetra_pak": ("https://jobs.tetrapak.com/", "en_GB"),
    }.get(portal["id"])
    if corrected:
        base, locale = corrected
        portal.update(career_url=base, listing_urls=[base + "search/"],
                      try_csb_json=True, try_tile_search=False,
                      csb_locales=[locale], targeted_max_csb_locales=1)
    if portal["id"] == "amkor":
        # Legacy RCM/JUIC search is incompatible with the current RMK/CSB collector.
        portal["enabled"] = False
        portal["disabled_reason"] = "Legacy RCM/JUIC; no compatible public RMK/CSB route confirmed (2026-09-18)."
